version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: ReportGenerator
    versions:
    - 4.8.7
  - dependency-name: Bogus.Text
    versions:
    - 33.0.2
